# Numpy Assignment

# Q.1. Write a function so that the columns of the output matrix are powers of the input vector. 

# The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1.

**HINT**:  Such  a  matrix  with  a  geometric  progression  in  each  row  is  named  for  AlexandreTheophile Vandermonde.

In [80]:
def gen_vand_mat(vect,n,increasing):
    vect = np.array(vect)
    m = vect.size
    mat = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            if increasing == True:
                mat[i,j] = mat[i,j] + vect[i]**(j+1)  
            elif increasing == False :
                mat[i,j] = mat[i,j] + vect[i]**(n - j) 
    return mat

In [81]:
a = gen_vand_mat([1,2,4,5,6],n = 3,increasing = True)
b = gen_vand_mat([1,2,4,5,6],n = 3,increasing = False)
print('When increasing is True ')
print(a)
print('-'*100)
print('When increasing is False ')
print(b)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

When increasing is True 
[[  1.   1.   1.]
 [  2.   4.   8.]
 [  4.  16.  64.]
 [  5.  25. 125.]
 [  6.  36. 216.]]
----------------------------------------------------------------------------------------------------
When increasing is False 
[[  1.   1.   1.]
 [  8.   4.   2.]
 [ 64.  16.   4.]
 [125.  25.   5.]
 [216.  36.   6.]]


# Q.2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i  1 2 3 4 5 6 7 8 9 10

=====  == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100 

y1   25 = (10+20+30+40)/4

y2  35 = (20+30+40+50)/4

y3  45 = (30+40+50+60)/4

y4  55 = (40+50+60+70)/4

y5  65 = (50+60+70+80)/4

y6  75 = (60+70+80+90)/4

y7  85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [111]:
def gen_mov_avg(seq,k):
    n = len(seq)
    for i in range(n-k+1):
        y = np.mean(seq[i:i+k])
        print('y_{} = {} '.format(i+1,y))

In [116]:
seq= list(range(10,110,10))
k = 4
gen_mov_avg(seq,k)

<IPython.core.display.Javascript object>

y_1 = 25.0 


<IPython.core.display.Javascript object>

y_2 = 35.0 


<IPython.core.display.Javascript object>

y_3 = 45.0 


<IPython.core.display.Javascript object>

y_4 = 55.0 


<IPython.core.display.Javascript object>

y_5 = 65.0 


<IPython.core.display.Javascript object>

y_6 = 75.0 


<IPython.core.display.Javascript object>

y_7 = 85.0 


# Q.3. Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [117]:
seq= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
gen_mov_avg(seq,k)

<IPython.core.display.Javascript object>

y_1 = 5.0 


<IPython.core.display.Javascript object>

y_2 = 4.666666666666667 


<IPython.core.display.Javascript object>

y_3 = 5.666666666666667 


<IPython.core.display.Javascript object>

y_4 = 6.666666666666667 


<IPython.core.display.Javascript object>

y_5 = 9.666666666666666 


<IPython.core.display.Javascript object>

y_6 = 28.666666666666668 


<IPython.core.display.Javascript object>

y_7 = 49.333333333333336 


<IPython.core.display.Javascript object>

y_8 = 72.66666666666667 


<IPython.core.display.Javascript object>

y_9 = 84.0 


<IPython.core.display.Javascript object>

y_10 = 93.33333333333333 


<IPython.core.display.Javascript object>

y_11 = 116.33333333333333 
